# Manipulation de données avec Pandas

### Introduction

In [2]:
import pandas as pd

fichier_in = "C:/Users/Thierno Barry/Documents/Python Scripts/01.Data Science - Analyse de données avec Python/00. Data/food_info.csv"
food_info = pd.read_csv(fichier_in)

col_names = food_info.columns.tolist()

In [2]:
print(col_names)

['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)', 'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)', 'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)', 'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)', 'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)', 'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)', 'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)', 'Vit_D_mcg', 'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)', 'Cholestrl_(mg)']

In [5]:
food_info.head(3)

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0

### Transformer une colonne

In [9]:
dev_1000 = food_info["Iron_(mg)"]/1000
dev_1000

0       0.00002
1       0.00016
2       0.00000
3       0.00031
4       0.00043
         ...
8613    0.00140
8614    0.00058
8615    0.00360
8616    0.00350
8617    0.00140
Name: Iron_(mg), Length: 8618, dtype: float64

In [10]:
iron = food_info["Iron_(mg)"]
iron

0       0.02
1       0.16
2       0.00
3       0.31
4       0.43
        ...
8613    1.40
8614    0.58
8615    3.60
8616    3.50
8617    1.40
Name: Iron_(mg), Length: 8618, dtype: float64

In [8]:
# Ajouter 100 à chaque aleur dans la colonne et retourne un nouvel object series
add_1000 = food_info["Iron_(mg)"] + 100

In [11]:
# Soustraire 100 à chaque aleur dans la colonne et retourne un nouvel object series
add_1000 = food_info["Iron_(mg)"] - 100

In [12]:
# Multiplie chaque valeur de la colonne par 2
mult_2 = food_info["Iron_(mg)"] * 2

#### Mission:
- Diviser la colonne "Sodium_(mg)" par 1000 pour convertir cette colonne en grammes et assigner le résultat à la variable sodium_grams.
- Multiplier la colonne "Sugar__Tot_(g)" par 1000 pour convertir en milligrammes et assigner le résultat à la variable sugar_milligrams.

In [13]:
sodium_grams = food_info["Sodium_(mg)"] / 1000
sugar_milligrams = food_info["Sugar_Tot_(g)"] * 1000

In [15]:
print(sodium_grams)

0       0.643
1       0.659
2       0.002
3       1.146
4       0.560
        ...
8613    4.450
8614    0.667
8615    0.058
8616    0.070
8617    0.068
Name: Sodium_(mg), Length: 8618, dtype: float64

In [16]:
print(sugar_milligrams)

0          60.0
1          60.0
2           0.0
3         500.0
4         510.0
         ...
8613        0.0
8614        0.0
8615    73200.0
8616        0.0
8617        0.0
Name: Sugar_Tot_(g), Length: 8618, dtype: float64

### Opérations mathématiques entre colonnes

In [3]:
water_energy = food_info["Water_(g)"] * food_info["Energ_Kcal"]

In [5]:
print(water_energy[0:5])

0    11378.79
1    11378.79
2      210.24
3    14970.73
4    15251.81
dtype: float64

In [6]:
print(food_info[["Water_(g)","Energ_Kcal"]][0:5])

   Water_(g)  Energ_Kcal
0      15.87         717
1      15.87         717
2       0.24         876
3      42.41         353
4      41.11         371

#### Mission:
- Diviser la colonne "Protein_(g)" par la colonne "Water_(g)" et assigner le résultat à la variable grams_of_protein_per_gram_of_water.
- Additionner les colonnes "Calcium_(mg)" et "Iron_(mg)" et assigner le résultat à la variable milligrams_of_calcium_and_iron.
- Afficher les résultats.

In [7]:
grams_of_protein_per_gram_of_water = food_info["Protein_(g)"] / food_info["Water_(g)"]
milligrams_of_calcium_and_iron = food_info["Calcium_(mg)"] + food_info["Iron_(mg)"]

In [8]:
print(grams_of_protein_per_gram_of_water)

0       0.053560
1       0.053560
2       1.166667
3       0.504598
4       0.565313
          ...
8613    0.430233
8614    0.292384
8615    0.000000
8616    0.203283
8617    0.252229
Length: 8618, dtype: float64

In [9]:
print(milligrams_of_calcium_and_iron)

0        24.02
1        24.16
2         4.00
3       528.31
4       674.43
         ...
8613     67.40
8614     10.58
8615     16.60
8616     13.50
8617    119.40
Length: 8618, dtype: float64

### Créer un indice nutritionnel

Score = 2 x (Protein_(g)) - 0.75 x (Lipid_Tot_(g))

#### Mission:
- Multiplier la colonne "Protein_(g)" par 2 et assigner le résultat à la variable protein.
- Multiplier la colonne "Lipid_Tot_(g)" par -0.75 et assigner le résultat à la variable fat.
- Additionner les variables ensemble et assigner le résultat à la variable rating.
- Afficher le résultat.

In [11]:
protein = food_info["Protein_(g)"] * 2
fat = food_info["Lipid_Tot_(g)"] * (-0.75)
rating = protein + fat
print(rating)

0      -59.1325
1      -59.1325
2      -74.0500
3       21.2450
4       24.2200
         ...
8613    18.1750
8614    40.4500
8615     0.0000
8616    31.1500
8617    39.2250
Length: 8618, dtype: float64

### Normaliser des colonnes

In [12]:
# Series.max()

In [14]:
# valeur maxde la colonne "Energ_Kcal"
max_calories = food_info["Energ_Kcal"].max()
print(max_calories)

902

In [16]:
# Diviser le valeurs de la colonne "Energ_Kcal" par la valeur max de cette même colonne
normalized_calories = food_info["Energ_Kcal"] / max_calories
print(normalized_calories)

0       0.794900
1       0.794900
2       0.971175
3       0.391353
4       0.411308
          ...
8613    0.338137
8614    0.123060
8615    0.298226
8616    0.099778
8617    0.098670
Name: Energ_Kcal, Length: 8618, dtype: float64

#### Mission:
- Normaliser les valeurs de la colonne "protein_(g)" et assigner le résultat à la variable normalized_protein.
- Normaliser les valeurs de la colonne "Lipid_Tot_(g)" et assigner le résultat à la variable normalized_fat.

In [6]:
max_protein = food_info["Protein_(g)"].max()
normalized_protein = food_info["Protein_(g)"] / max_protein
print(normalized_protein)

0       0.009624
1       0.009624
2       0.003170
3       0.242301
4       0.263134
          ...
8613    0.209466
8614    0.232563
8615    0.000000
8616    0.182292
8617    0.224185
Name: Protein_(g), Length: 8618, dtype: float64

In [7]:
max_fat = food_info["Lipid_Tot_(g)"].max()
normalized_fat = food_info["Lipid_Tot_(g)"] / max_fat
print(normalized_fat)

0       0.8111
1       0.8111
2       0.9948
3       0.2874
4       0.2968
         ...
8613    0.2510
8614    0.0084
8615    0.0000
8616    0.0140
8617    0.0050
Name: Lipid_Tot_(g), Length: 8618, dtype: float64

### Créer une nouvelle colonne

In [4]:
iron_grams = food_info["Iron_(mg)"] / 100
food_info["Iron_(g)"] = iron_grams

In [5]:
food_info

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.0002
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.0016
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.0000
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0,0.0031
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.0043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.00,...,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0,0.0140
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.00,...,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0,0.0058
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.20,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.0360
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.00,...,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0,0.0350
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.00,...,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0,0.0140

#### Mission:
- Assigner la colonne normalisée représentée par la variable normalized_protein à la nouvelle colonne qu'on nommera "Normalized_Protein" dans le dataframe food_info.
- Assigner la colonne normalisée représentée par la variable normalized_fat à la nouvelle colonne qu'on nommera "Normalized_Fat" dans la dataframe food_info.
- Afficher les 5 premières valeurs du dataframe food_info.

In [8]:
food_info["Normalized_Protein"] = normalized_protein
food_info["Normalized_Fat"] = normalized_fat

In [9]:
food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_Fat
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.0002,0.009624,0.8111
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.0016,0.009624,0.8111
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.0000,0.003170,0.9948
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,0.5,21.0,2.4,18.669,7.778,0.800,75.0,0.0031,0.242301,0.2874
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.0043,0.263134,0.2968

### Créer une colonne pour l'indice nutritionnel normalisé

Score = 2 x Normalized_Protein - 0.75 x Normalized_Fat

#### Mission:
- Utiliser les colonnes Normalized_Protein et Normalized_Fat avec cette formule pour créer une nouvelle colonne qu'on nommera Norm_Nutr_Index.

In [10]:
food_info["Norm_Nutr_Index"] = 2 * food_info["Normalized_Protein"] + (-0.75)*food_info["Normalized_Fat"]

In [11]:
food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_Fat,Norm_Nutr_Index
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,60.0,7.0,51.368,21.021,3.043,215.0,0.0002,0.009624,0.8111,-0.589077
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,60.0,7.0,50.489,23.426,3.012,219.0,0.0016,0.009624,0.8111,-0.589077
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,73.0,8.6,61.924,28.732,3.694,256.0,0.0000,0.003170,0.9948,-0.739759
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,21.0,2.4,18.669,7.778,0.800,75.0,0.0031,0.242301,0.2874,0.269051
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,22.0,2.5,18.764,8.598,0.784,94.0,0.0043,0.263134,0.2968,0.303668

### Trier un DataFrame

In [15]:
# sort_values()

In [14]:
food_info.sort_values("Sodium_(mg)")

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_Fat,Norm_Nutr_Index
760,4666,SHORTENING INDUSTRIAL SOY (PARTIALLY HYDR )&CO...,0.00,884,0.00,100.00,0.00,0.00,0.0,0.00,...,0.0,43.0,17.416,40.824,36.038,0.0,0.0000,0.000000,1.0000,-0.750000
758,4664,OIL INDUSTRIAL SOY (PARTHYDR ) PALM ICINGS & ...,0.00,884,0.00,100.00,0.00,0.00,0.0,0.00,...,NaN,24.7,28.421,59.715,7.095,0.0,0.0000,0.000000,1.0000,-0.750000
405,3168,BABYFOOD JUC APPL&PEACH,89.00,43,0.20,0.10,0.30,10.50,0.1,9.59,...,0.0,0.5,0.018,0.002,0.031,0.0,0.0056,0.002264,0.0010,0.003779
761,4667,SHORTENING INDUS SOY (PART HYDR ) FOR BAKING &...,0.00,884,0.00,100.00,0.00,0.00,0.0,0.00,...,NaN,43.0,18.788,71.023,5.400,0.0,0.0000,0.000000,1.0000,-0.750000
2269,9111,GRAPEFRUIT RAW PINK&RED&WHITE ALL AREAS,90.89,32,0.63,0.10,0.31,8.08,1.1,6.98,...,0.0,0.0,0.014,0.013,0.024,0.0,0.0009,0.007133,0.0010,0.013516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8184,35092,WILLOW LEAVES IN OIL (ALASKA NATIVE),28.00,592,2.60,61.00,0.30,8.10,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0130,0.029438,0.6100,-0.398623
8185,35093,WILLOW YOUNG LEAVES CHOPD (ALASKA NATIVE),68.70,122,6.10,1.60,2.90,20.70,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0260,0.069067,0.0160,0.126134
8195,35139,SQUASH INDIAN CKD BLD (NAVAJO),96.21,16,0.31,0.15,0.10,3.22,1.5,2.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003510,0.0015,0.005895
8251,35199,PRICKLY PEARS BRLD (NORTHERN PLAINS INDIANS),75.83,91,0.39,0.31,1.90,21.57,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004416,0.0031,0.006507
8267,35231,SEA LION STELLER FAT (ALASKA NATIVE),4.70,850,0.90,94.00,0.20,0.00,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,95.0,NaN,0.010190,0.9400,-0.684620

In [16]:
# Trie le dataframe et remplace l'ancien dataframe
food_info.sort_values("Sodium_(mg)", inplace=True)

In [17]:
food_info

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_Fat,Norm_Nutr_Index
760,4666,SHORTENING INDUSTRIAL SOY (PARTIALLY HYDR )&CO...,0.00,884,0.00,100.00,0.00,0.00,0.0,0.00,...,0.0,43.0,17.416,40.824,36.038,0.0,0.0000,0.000000,1.0000,-0.750000
758,4664,OIL INDUSTRIAL SOY (PARTHYDR ) PALM ICINGS & ...,0.00,884,0.00,100.00,0.00,0.00,0.0,0.00,...,NaN,24.7,28.421,59.715,7.095,0.0,0.0000,0.000000,1.0000,-0.750000
405,3168,BABYFOOD JUC APPL&PEACH,89.00,43,0.20,0.10,0.30,10.50,0.1,9.59,...,0.0,0.5,0.018,0.002,0.031,0.0,0.0056,0.002264,0.0010,0.003779
761,4667,SHORTENING INDUS SOY (PART HYDR ) FOR BAKING &...,0.00,884,0.00,100.00,0.00,0.00,0.0,0.00,...,NaN,43.0,18.788,71.023,5.400,0.0,0.0000,0.000000,1.0000,-0.750000
2269,9111,GRAPEFRUIT RAW PINK&RED&WHITE ALL AREAS,90.89,32,0.63,0.10,0.31,8.08,1.1,6.98,...,0.0,0.0,0.014,0.013,0.024,0.0,0.0009,0.007133,0.0010,0.013516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8184,35092,WILLOW LEAVES IN OIL (ALASKA NATIVE),28.00,592,2.60,61.00,0.30,8.10,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0130,0.029438,0.6100,-0.398623
8185,35093,WILLOW YOUNG LEAVES CHOPD (ALASKA NATIVE),68.70,122,6.10,1.60,2.90,20.70,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0260,0.069067,0.0160,0.126134
8195,35139,SQUASH INDIAN CKD BLD (NAVAJO),96.21,16,0.31,0.15,0.10,3.22,1.5,2.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003510,0.0015,0.005895
8251,35199,PRICKLY PEARS BRLD (NORTHERN PLAINS INDIANS),75.83,91,0.39,0.31,1.90,21.57,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004416,0.0031,0.006507
8267,35231,SEA LION STELLER FAT (ALASKA NATIVE),4.70,850,0.90,94.00,0.20,0.00,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,95.0,NaN,0.010190,0.9400,-0.684620

In [19]:
# Trie décroissant du dataframe et remplace l'ancien dataframe
food_info.sort_values("Sodium_(mg)", inplace=True, ascending=False)

In [20]:
food_info

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_Fat,Norm_Nutr_Index
276,2047,SALT TABLE,0.20,0,0.00,0.00,99.8,0.00,0.0,0.00,...,0.0,0.0,0.000,0.000,0.000,0.0,0.0033,0.000000,0.0000,0.000000
5814,18372,LEAVENING AGENTS BAKING SODA,0.20,0,0.00,0.00,36.9,0.00,0.0,0.00,...,0.0,0.0,0.000,0.000,0.000,0.0,0.0000,0.000000,0.0000,0.000000
6192,19225,DESSERTS RENNIN TABLETS UNSWTND,6.50,84,1.00,0.10,72.5,19.80,0.0,NaN,...,NaN,NaN,0.041,0.038,0.007,0.0,0.0707,0.011322,0.0010,0.021895
1242,6075,SOUP BF BROTH OR BOUILLON PDR DRY,3.27,213,15.97,8.89,54.5,17.40,0.0,16.71,...,0.0,3.2,4.320,3.616,0.332,10.0,0.0100,0.180820,0.0889,0.294964
1245,6081,SOUP CHICK BROTH CUBES DRY,2.50,198,14.60,4.70,54.7,23.50,0.0,0.00,...,NaN,0.0,1.200,1.920,1.620,13.0,0.0187,0.165308,0.0470,0.295366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8184,35092,WILLOW LEAVES IN OIL (ALASKA NATIVE),28.00,592,2.60,61.00,0.3,8.10,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0130,0.029438,0.6100,-0.398623
8185,35093,WILLOW YOUNG LEAVES CHOPD (ALASKA NATIVE),68.70,122,6.10,1.60,2.9,20.70,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0260,0.069067,0.0160,0.126134
8195,35139,SQUASH INDIAN CKD BLD (NAVAJO),96.21,16,0.31,0.15,0.1,3.22,1.5,2.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003510,0.0015,0.005895
8251,35199,PRICKLY PEARS BRLD (NORTHERN PLAINS INDIANS),75.83,91,0.39,0.31,1.9,21.57,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004416,0.0031,0.006507
8267,35231,SEA LION STELLER FAT (ALASKA NATIVE),4.70,850,0.90,94.00,0.2,0.00,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,95.0,NaN,0.010190,0.9400,-0.684620

#### Mission:
- Remplacer le dataframe food_info en triant par rapport à la colonne Norm_Nutr_Index de façon décroissante (du plus grand au plus petit)

In [21]:
food_info.sort_values("Norm_Nutr_Index", inplace=True, ascending=False)

In [22]:
food_info

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Iron_(g),Normalized_Protein,Normalized_Fat,Norm_Nutr_Index
4991,16423,SOY PROT ISOLATE K TYPE CRUDE PROT BASIS,4.98,321,88.32,0.53,3.58,2.59,2.0,0.0,...,0.0,0.0,0.066,0.101,0.258,0.0,0.1450,1.000000,0.0053,1.996025
6155,19177,GELATINS DRY PDR UNSWTND,13.00,335,85.60,0.10,1.30,0.00,0.0,0.0,...,0.0,0.0,0.070,0.060,0.010,0.0,0.0111,0.969203,0.0010,1.937656
216,1258,EGG WHITE DRIED STABILIZED GLUCOSE RED,6.53,362,84.63,0.48,3.63,4.72,0.0,0.0,...,0.0,0.0,0.147,0.173,0.070,20.0,0.0023,0.958220,0.0048,1.912840
124,1136,EGG WHITE DRIED PDR STABILIZED GLUCOSE RED,8.54,376,82.40,0.04,4.55,4.47,0.0,0.0,...,0.0,0.0,0.000,0.000,0.000,0.0,0.0024,0.932971,0.0004,1.865642
8152,35055,SEAL BEARDED (OOGRUK) MEAT DRIED (ALASKA NATIVE),11.60,351,82.60,2.30,3.50,0.00,0.0,0.0,...,NaN,NaN,0.600,1.330,0.370,NaN,0.4960,0.935236,0.0230,1.853221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,4001,FAT BEEF TALLOW,0.00,902,0.00,100.00,0.00,0.00,0.0,0.0,...,28.0,0.0,49.800,41.800,4.000,109.0,0.0000,0.000000,1.0000,-0.750000
703,4591,FISH OIL MENHADEN,0.00,902,0.00,100.00,0.00,0.00,0.0,NaN,...,NaN,NaN,30.427,26.694,34.197,521.0,0.0000,0.000000,1.0000,-0.750000
790,4701,OIL INDUSTRIAL SOY FULLY HYDR,0.00,884,0.00,100.00,0.00,0.00,0.0,0.0,...,0.0,183.9,93.966,1.341,0.383,0.0,0.0005,0.000000,1.0000,-0.750000
789,4700,OIL INDUSTRIAL SOY ULTRA LO LINOLENIC,0.00,884,0.00,100.00,0.00,0.00,0.0,0.0,...,0.0,183.9,14.853,28.876,52.149,0.0,0.0005,0.000000,1.0000,-0.750000
631,4037,OIL RICE BRAN,0.00,884,0.00,100.00,0.00,0.00,0.0,0.0,...,NaN,24.7,19.700,39.300,35.000,0.0,0.0007,0.000000,1.0000,-0.750000